<a href="https://colab.research.google.com/github/sudharsan0503/DL/blob/main/DL1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd
import tensorflow as tf
from tensorflow import keras
from sklearn.model_selection import train_test_split
from tensorflow.keras import layers

In [ ]:
df= pd.DataFrame({
    "soil_moisture":[0.10,0.15,0.20,0.25,0.40,0.60,0.35,0.18,
                     0.45,0.05,0.80,0.27,0.55,0.70,0.12,0.30],
    "temperature_c":[34,30,26,22,28,30,19,22,
                     35,24,33,33,21,25,20,29],
    "sunlight_hours":[9,8,7,4,8,10,3,10,12,5,9,11,2,6,1,9],
    "needs_water":[1,1,1,0,0,0,0,1,0,1,0,1,0,0,1,1]
})

In [ ]:
df

    soil_moisture  temperature_c  sunlight_hours  needs_water
0            0.10             34               9            1
1            0.15             30               8            1
2            0.20             26               7            1
3            0.25             22               4            0
4            0.40             28               8            0
5            0.60             30              10            0
6            0.35             19               3            0
7            0.18             22              10            1
8            0.45             35              12            0
9            0.05             24               5            1
10           0.80             33               9            0
11           0.27             33              11            1
12           0.55             21               2            0
13           0.70             25               6            0
14           0.12             20               1            1
15           0.30             29               9            1

In [ ]:
df.columns

Index(['soil_moisture', 'temperature_c', 'sunlight_hours', 'needs_water'], dtype='object')

In [ ]:
X=df[['soil_moisture', 'temperature_c', 'sunlight_hours']]
y=df[['needs_water']]

In [ ]:
X_min=X.min()
X_max=X.max()
X_scaled=(X-X_min)/(X_max-X_min+1e-8)

In [ ]:
X_scaled

    soil_moisture  temperature_c  sunlight_hours
0        0.066667         0.9375        0.727273
1        0.133333         0.6875        0.636364
2        0.200000         0.4375        0.545455
3        0.266667         0.1875        0.272727
4        0.466667         0.5625        0.636364
5        0.733333         0.6875        0.818182
6        0.400000         0.0000        0.181818
7        0.173333         0.1875        0.818182
8        0.533333         1.0000        1.000000
9        0.000000         0.3125        0.363636
10       1.000000         0.8750        0.727273
11       0.293333         0.8750        0.909091
12       0.666667         0.1250        0.090909
13       0.866667         0.3750        0.454545
14       0.093333         0.0625        0.000000
15       0.333333         0.6250        0.727273

In [ ]:
X_train,X_test,y_train,y_test = train_test_split(X_scaled,y,test_size=0.25,random_state=42)

In [ ]:
model = keras.Sequential([
    layers.Input(shape=(X_train.shape[1],)),
    layers.Dense(8, activation='relu'),
    layers.Dense(1, activation='sigmoid')#output
])

In [ ]:
model.compile(optimizer='sgd',loss='binary_crossentropy',metrics=['accuracy'])

In [ ]:
history = model.fit(
    X_train.values,y_train.values,
    validation_data=(X_test.values,y_test.values),
    epochs=100,
    batch_size=4,
    verbose=1
    )

Epoch 1/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 1s 109ms/step - accuracy: 0.7500 - loss: 0.6578 - val_accuracy: 0.5000 - val_loss: 0.6115
Epoch 2/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - accuracy: 0.7500 - loss: 0.6566 - val_accuracy: 0.5000 - val_loss: 0.6119
Epoch 3/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - accuracy: 0.7500 - loss: 0.6561 - val_accuracy: 0.5000 - val_loss: 0.6123
Epoch 4/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - accuracy: 0.7500 - loss: 0.6545 - val_accuracy: 0.5000 - val_loss: 0.6126
Epoch 5/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - accuracy: 0.8333 - loss: 0.6540 - val_accuracy: 0.5000 - val_loss: 0.6130
Epoch 6/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - accuracy: 0.8333 - loss: 0.6530 - val_accuracy: 0.5000 - val_loss: 0.6134
Epoch 7/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 60ms/step - accuracy: 0.8333 - loss: 0.6513 - val_accuracy: 0.5000 - val_loss: 0.6137
Epoch 8/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 65ms/step - accuracy: 0.8333 - loss: 0.6507 - val_accuracy: 0.5000 - val_loss: 0.6141
Epoch 9/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 70ms/step - accuracy: 0.8333 - loss: 0.6494 - val_accuracy: 0.5000 - val_loss: 0.6146
Epoch 10/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step - accuracy: 0.8333 - loss: 0.6485 - val_accuracy: 0.5000 - val_loss: 0.6151
Epoch 11/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step - accuracy: 0.8333 - loss: 0.6483 - val_accuracy: 0.5000 - val_loss: 0.6157
Epoch 12/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step - accuracy: 0.8333 - loss: 0.6472 - val_accuracy: 0.5000 - val_loss: 0.6162
Epoch 13/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 62ms/step - accuracy: 0.8333 - loss: 0.6459 - val_accuracy: 0.5000 - val_loss: 0.6167
Epoch 14/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step - accuracy: 0.8333 - loss: 0.6447 - val_accuracy: 0.5000 - val_loss: 0.6173
Epoch 15/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 63ms/step - accuracy: 0.8333 - loss: 0.6439 - val_accuracy: 0.5000 - val_loss: 0.6178
Epoch 16/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 65ms/step - accuracy: 0.8333 - loss: 0.6430 - val_accuracy: 0.5000 - val_loss: 0.6183
Epoch 17/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 46ms/step - accuracy: 0.8333 - loss: 0.6428 - val_accuracy: 0.5000 - val_loss: 0.6188
Epoch 18/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step - accuracy: 0.8333 - loss: 0.6413 - val_accuracy: 0.5000 - val_loss: 0.6193
Epoch 19/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 52ms/step - accuracy: 0.8333 - loss: 0.6404 - val_accuracy: 0.7500 - val_loss: 0.6198
Epoch 20/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step - accuracy: 0.8333 - loss: 0.6396 - val_accuracy: 0.7500 - val_loss: 0.6203
Epoch 21/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step - accuracy: 0.8333 - loss: 0.6390 - val_accuracy: 0.7500 - val_loss: 0.6208
Epoch 22/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 61ms/step - accuracy: 0.8333 - loss: 0.6390 - val_accuracy: 0.7500 - val_loss: 0.6212
Epoch 23/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 58ms/step - accuracy: 0.8333 - loss: 0.6371 - val_accuracy: 0.7500 - val_loss: 0.6217
Epoch 24/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step - accuracy: 0.8333 - loss: 0.6363 - val_accuracy: 0.7500 - val_loss: 0.6222
Epoch 25/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - accuracy: 0.8333 - loss: 0.6355 - val_accuracy: 0.7500 - val_loss: 0.6227
Epoch 26/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - accuracy: 0.8333 - loss: 0.6346 - val_accuracy: 0.7500 - val_loss: 0.6232
Epoch 27/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - accuracy: 0.8333 - loss: 0.6340 - val_accuracy: 0.7500 - val_loss: 0.6237
Epoch 28/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - accuracy: 0.8333 - loss: 0.6338 - val_accuracy: 0.7500 - val_loss: 0.6241
Epoch 29/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - accuracy: 0.8333 - loss: 0.6323 - val_accuracy: 0.7500 - val_loss: 0.6246
Epoch 30/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - accuracy: 0.8333 - loss: 0.6314 - val_accuracy: 0.7500 - val_loss: 0.6251
Epoch 31/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - accuracy: 0.8333 - loss: 0.6308 - val_accuracy: 0.7500 - val_loss: 0.6255
Epoch 32/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - accuracy: 0.9167 - loss: 0.6298 - val_accuracy: 0.7500 - val_loss: 0.6260
Epoch 33/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - accuracy: 0.9167 - loss: 0.6291 - val_accuracy: 0.7500 - val_loss: 0.6265
Epoch 34/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - accuracy: 0.9167 - loss: 0.6288 - val_accuracy: 0.7500 - val_loss: 0.6269
Epoch 35/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - accuracy: 0.9167 - loss: 0.6274 - val_accuracy: 0.7500 - val_loss: 0.6274
Epoch 36/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - accuracy: 0.9167 - loss: 0.6272 - val_accuracy: 0.7500 - val_loss: 0.6279
Epoch 37/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - accuracy: 0.9167 - loss: 0.6262 - val_accuracy: 0.7500 - val_loss: 0.6284
Epoch 38/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - accuracy: 0.9167 - loss: 0.6252 - val_accuracy: 0.7500 - val_loss: 0.6288
Epoch 39/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - accuracy: 0.9167 - loss: 0.6256 - val_accuracy: 0.7500 - val_loss: 0.6293
Epoch 40/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - accuracy: 0.9167 - loss: 0.6244 - val_accuracy: 0.7500 - val_loss: 0.6297
Epoch 41/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - accuracy: 0.9167 - loss: 0.6228 - val_accuracy: 0.7500 - val_loss: 0.6302
Epoch 42/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - accuracy: 0.9167 - loss: 0.6220 - val_accuracy: 0.7500 - val_loss: 0.6306
Epoch 43/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - accuracy: 0.9167 - loss: 0.6222 - val_accuracy: 0.7500 - val_loss: 0.6310
Epoch 44/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - accuracy: 0.9167 - loss: 0.6213 - val_accuracy: 0.7500 - val_loss: 0.6315
Epoch 45/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - accuracy: 0.9167 - loss: 0.6197 - val_accuracy: 0.7500 - val_loss: 0.6319
Epoch 46/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - accuracy: 0.9167 - loss: 0.6198 - val_accuracy: 0.7500 - val_loss: 0.6323
Epoch 47/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - accuracy: 0.9167 - loss: 0.6188 - val_accuracy: 0.7500 - val_loss: 0.6327
Epoch 48/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - accuracy: 0.9167 - loss: 0.6182 - val_accuracy: 0.7500 - val_loss: 0.6330
Epoch 49/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - accuracy: 0.9167 - loss: 0.6175 - val_accuracy: 0.7500 - val_loss: 0.6334
Epoch 50/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - accuracy: 0.9167 - loss: 0.6170 - val_accuracy: 0.7500 - val_loss: 0.6338
Epoch 51/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - accuracy: 0.9167 - loss: 0.6160 - val_accuracy: 0.7500 - val_loss: 0.6341
Epoch 52/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - accuracy: 0.9167 - loss: 0.6154 - val_accuracy: 0.7500 - val_loss: 0.6345
Epoch 53/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - accuracy: 0.9167 - loss: 0.6146 - val_accuracy: 0.7500 - val_loss: 0.6348
Epoch 54/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - accuracy: 0.9167 - loss: 0.6141 - val_accuracy: 0.7500 - val_loss: 0.6351
Epoch 55/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step - accuracy: 0.9167 - loss: 0.6129 - val_accuracy: 0.7500 - val_loss: 0.6354
Epoch 56/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - accuracy: 0.9167 - loss: 0.6130 - val_accuracy: 0.7500 - val_loss: 0.6356
Epoch 57/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - accuracy: 0.9167 - loss: 0.6115 - val_accuracy: 0.7500 - val_loss: 0.6359
Epoch 58/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - accuracy: 0.9167 - loss: 0.6109 - val_accuracy: 0.7500 - val_loss: 0.6362
Epoch 59/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 105ms/step - accuracy: 0.9167 - loss: 0.6102 - val_accuracy: 0.7500 - val_loss: 0.6364
Epoch 60/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 102ms/step - accuracy: 0.9167 - loss: 0.6098 - val_accuracy: 0.7500 - val_loss: 0.6367
Epoch 61/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 98ms/step - accuracy: 0.9167 - loss: 0.6093 - val_accuracy: 0.7500 - val_loss: 0.6369
Epoch 62/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 64ms/step - accuracy: 0.9167 - loss: 0.6083 - val_accuracy: 0.7500 - val_loss: 0.6371
Epoch 63/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 98ms/step - accuracy: 0.9167 - loss: 0.6076 - val_accuracy: 0.7500 - val_loss: 0.6374
Epoch 64/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - accuracy: 0.9167 - loss: 0.6072 - val_accuracy: 0.7500 - val_loss: 0.6376
Epoch 65/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - accuracy: 0.9167 - loss: 0.6069 - val_accuracy: 0.7500 - val_loss: 0.6378
Epoch 66/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - accuracy: 0.9167 - loss: 0.6062 - val_accuracy: 0.7500 - val_loss: 0.6380
Epoch 67/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - accuracy: 0.9167 - loss: 0.6052 - val_accuracy: 0.7500 - val_loss: 0.6383
Epoch 68/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - accuracy: 0.9167 - loss: 0.6045 - val_accuracy: 0.7500 - val_loss: 0.6385
Epoch 69/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - accuracy: 0.9167 - loss: 0.6043 - val_accuracy: 0.7500 - val_loss: 0.6387
Epoch 70/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - accuracy: 0.9167 - loss: 0.6033 - val_accuracy: 0.7500 - val_loss: 0.6389
Epoch 71/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - accuracy: 0.9167 - loss: 0.6027 - val_accuracy: 0.7500 - val_loss: 0.6390
Epoch 72/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - accuracy: 0.9167 - loss: 0.6023 - val_accuracy: 0.7500 - val_loss: 0.6392
Epoch 73/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - accuracy: 0.9167 - loss: 0.6010 - val_accuracy: 0.7500 - val_loss: 0.6394
Epoch 74/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - accuracy: 0.8333 - loss: 0.6010 - val_accuracy: 0.7500 - val_loss: 0.6395
Epoch 75/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - accuracy: 0.8333 - loss: 0.5999 - val_accuracy: 0.7500 - val_loss: 0.6397
Epoch 76/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - accuracy: 0.8333 - loss: 0.5993 - val_accuracy: 0.7500 - val_loss: 0.6398
Epoch 77/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - accuracy: 0.9167 - loss: 0.5984 - val_accuracy: 0.7500 - val_loss: 0.6400
Epoch 78/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - accuracy: 0.8333 - loss: 0.5981 - val_accuracy: 0.7500 - val_loss: 0.6401
Epoch 79/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - accuracy: 0.8333 - loss: 0.5972 - val_accuracy: 0.7500 - val_loss: 0.6402
Epoch 80/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - accuracy: 0.8333 - loss: 0.5966 - val_accuracy: 0.7500 - val_loss: 0.6403
Epoch 81/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - accuracy: 0.8333 - loss: 0.5963 - val_accuracy: 0.7500 - val_loss: 0.6404
Epoch 82/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - accuracy: 0.8333 - loss: 0.5953 - val_accuracy: 0.7500 - val_loss: 0.6406
Epoch 83/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 61ms/step - accuracy: 0.8333 - loss: 0.5950 - val_accuracy: 0.7500 - val_loss: 0.6407
Epoch 84/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 74ms/step - accuracy: 0.7500 - loss: 0.5939 - val_accuracy: 0.7500 - val_loss: 0.6408
Epoch 85/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 146ms/step - accuracy: 0.8333 - loss: 0.5937 - val_accuracy: 0.7500 - val_loss: 0.6409
Epoch 86/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - accuracy: 0.7500 - loss: 0.5933 - val_accuracy: 0.7500 - val_loss: 0.6410
Epoch 87/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - accuracy: 0.7500 - loss: 0.5924 - val_accuracy: 0.7500 - val_loss: 0.6410
Epoch 88/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 54ms/step - accuracy: 0.7500 - loss: 0.5913 - val_accuracy: 0.7500 - val_loss: 0.6411
Epoch 89/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 124ms/step - accuracy: 0.7500 - loss: 0.5909 - val_accuracy: 0.7500 - val_loss: 0.6412
Epoch 90/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - accuracy: 0.7500 - loss: 0.5901 - val_accuracy: 0.7500 - val_loss: 0.6412
Epoch 91/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 52ms/step - accuracy: 0.7500 - loss: 0.5900 - val_accuracy: 0.7500 - val_loss: 0.6413
Epoch 92/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - accuracy: 0.7500 - loss: 0.5890 - val_accuracy: 0.7500 - val_loss: 0.6413
Epoch 93/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - accuracy: 0.7500 - loss: 0.5882 - val_accuracy: 0.7500 - val_loss: 0.6413
Epoch 94/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 60ms/step - accuracy: 0.7500 - loss: 0.5882 - val_accuracy: 0.7500 - val_loss: 0.6414
Epoch 95/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 110ms/step - accuracy: 0.7500 - loss: 0.5869 - val_accuracy: 0.7500 - val_loss: 0.6414
Epoch 96/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 103ms/step - accuracy: 0.7500 - loss: 0.5864 - val_accuracy: 0.7500 - val_loss: 0.6414
Epoch 97/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 152ms/step - accuracy: 0.7500 - loss: 0.5859 - val_accuracy: 0.7500 - val_loss: 0.6415
Epoch 98/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 100ms/step - accuracy: 0.7500 - loss: 0.5857 - val_accuracy: 0.7500 - val_loss: 0.6415
Epoch 99/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 174ms/step - accuracy: 0.8333 - loss: 0.5849 - val_accuracy: 0.7500 - val_loss: 0.6415
Epoch 100/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 87ms/step - accuracy: 0.8333 - loss: 0.5841 - val_accuracy: 0.7500 - val_loss: 0.6415

In [ ]:
from tensorflow.keras import optimizers

In [ ]:
opt = optimizers.SGD(learning_rate=0.00,momentum=0.9)